var lyricData = [
	{en: ["It's been a long day without you my friend"], ko: "네가 떠난 지금 오늘은 너무 긴 하루였어", time: 10.6},
	{en: ["And I tell you all about it when I see you again"], ko: "널 다시 만나면 모든 이야기를 들려줄게", time: 17.3},
	{en: ["We've come _ ____ ___ from where we bagan", "We've come a long way from where we bagan"], ko: "처음 시작했던 때부터 참 많이도 왔다", time: 22.5, stop: 28.8},
	{en: ["Oh I'll tell you all about it when I see you again"], ko: "널 다시 만나면 모든 이야기를 들려줄게", time: 29.2},
	{en: ["When I see you again"], ko: "널 다시 만나면", time: 35.1},
	{en: ["Damn who knew all the planes we flew"], ko: "우린 함께 수없이 많은 하늘을 날았지", time: 40.0},
	{en: ["Good things we've ____ _______", "Good things we've been through"], ko: "기쁜 일도 함께 겪었지", time: 42.7, stop: 44.58},
	{en: ["That I'll be standing right here"], ko: "난 여기에 서서", time: 44.8},
	{en: ["Talking to you about another path"], ko: "다른 길을 가자고 말했어", time: 46.3},
	{en: ["I know we loved to hit the road and laugh"], ko: "함께 달리며 또 웃었지만", time: 49.0},
	{en: ["But something told me that it wouldn't last"], ko: "그게 영원할 수 없음을 알아버렸어", time: 51.0},
	{en: ["Had to switch up look at things different see the bigger picture"], ko: "우린 더 넓은 세상을 다른시각으로 보고 더 크게 봐야했어", time: 53.4},
	{en: ["Those were the days hard work forever pays"], ko: "그땐 힘들었지만, 우린 행복했었어", time: 57.2},
	{en: ["now I see you __ _ ______ _____", "now I see you in a better place"], ko: "이제 넌 더 좋은 곳에 있겠지", time: 60.2, stop: 62.37},
	{en: ["How could we not talk about family when familys all that we got?"], ko: "어떻게 가족을 잊을 수 있을까? 우리에겐 가족이 전부인 걸", time: 65.0},
	{en: ["Everything I went through you were standing there by my side"], ko: "내가 걸어온 길엔 늘 네가 함께 했지", time: 68.4},
	{en: ["And now you gonna be with me for the last ride"], ko: "마지막 이 길에도 넌 함께 할거야", time: 71.3},
	{en: ["It's been a long day without you my friend"], ko: "네가 떠난 지금 오늘은 너무 긴 하루였어", time: 74.0},
	{en: ["And I'll tell you all about it when I see you again"], ko: "널 다시 만나면 모든 이야기를 들려줄게", time: 80.6},
	{en: ["We've come a long way from where we began"], ko: "처음 시작했던 때부터 참 많이도 왔다", time: 85.9},
	{en: ["Oh I'll tell you all about it when I see you again"], ko: "널 다시 만나면 모든 이야기를 들려줄게", time: 91.8},
	{en: ["When I see you again"], ko: "널 다시 만나면", time: 98.0},
	{en: ["First you both go out your way"], ko: "처음엔 다른 길을 걸었지만", time: 116.0},
	{en: ["And the vibe is feeling strong and whats"], ko: "우리는 서로를 강하게 느꼇어", time: 117.9},
	{en: ["Small turn to a friendship"], ko: "그렇게 우리는 친구가 되고", time: 119.5},
	{en: ["a friendship turn into a bond"], ko: "친구는 형제가 됐어.", time: 121.0},
	{en: ["and that bond will never  be broke"], ko: "그리고 형제는 절대 헤어지지 않고", time: 122.8},
	{en: ["and the love will _____ ___ ____", "and the love will never get lost"], ko: "형제에게 이별은 없어", time: 123.8, stop: 125.78},
	{en: ["And when brotherhood come first then the line will never be crossed"], ko: "형제애가 소중한 사람은 선을 넘지 않아", time: 128.2},
	{en: ["established it on our own"], ko: "스스로 정한 원칙에서", time: 131.1},
	{en: ["When that line had to be drawn"], ko: "그 선은 그어져야만 했고", time: 133.1},
	{en: ["and that line is what we reach"], ko: "우리가 그 선에 닿게 되면", time: 134.2},
	{en: ["so ________ __ when I'm gone", "so remember me when I'm gone"], ko: "내가 가더라도 날 기억해줘", time: 136.0, stop: 137.63},
	{en: ["How could we not talk about family when familys all that we got?"], ko: "어떻게 가족을 잊을 수 있을까? 우리에겐 가족이 전부인 걸", time: 140.0},
	{en: ["Everything I went through you were standing there by my side"], ko: "내가 걸어온 길엔 늘 네가 함께 했지", time: 143.4},
	{en: ["And now you gonna be with me for the last ride"], ko: "마지막 이 길에도 넌 함께 할거야", time: 146.3},
	{en: ["So let the light guide your way hold every memory"], ko: "이 길을 비추는 저 불빛처럼, 모든 순간을 기억해줘", time: 148.2},
	{en: ["As you go and every road you take will always ____ ___ ____", "As you go and every road you take will always lead you home"], ko: "어느 길로 가든 넌 가족에게 돌아올거야", time: 158.0, stop: 168.49},
	{en: ["​It's been a long day without you my friend"], ko: "네가 떠난 지금 오늘은 너무 긴 하루였어", time: 172.5},
	{en: ["And I'll tell you all about it when I see you again"], ko: "널 다시 만나면 모든 이야기를 들려줄게", time: 179.2},
	{en: ["We've come a long way from where we began"], ko: "처음 시작했던 때부터 참 많이도 왔다", time: 184.4},
	{en: ["Oh I'll tell you all about it when I see you again"], ko: "널 다시 만나면 모든 이야기를 들려줄게", time: 191.2},
	{en: ["When I see you again"], ko: "널 다시 만나면", time: 196.0}
];